### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by dgmstuart** [TweetPressFr/jm-twitter-cards#53]
Hello - I need to contact you about a security Issue in this plugin. I'm sorry to communicate publicly like this, but I've tried using the contact form at http://www.tweetpress.fr/contact/, and contacting you on Twitter and I haven't had a response. 

Can you please email security@dxw.com so that I can send you details of the issue.

Many thanks

**Comment by TweetPressFr** [comment]
Very sorry for the delay but I did not reveive anything. Please try again the form, I'll answer quickly.

**Comment by dgmstuart** [comment]
OK, I've done it, and it said that "Votre message a bien été envoyé", but I'm thinking maybe the message is too long or your mail client thinks it's spam. If you don't have anything in your inbox, please send an email directly to security@dxw.com so that I can reply with the details.

**Comment by dgmstuart** [comment]
Hi - I haven't heard from you. Did you recieve the report?

**Comment by TweetPressFr** [comment]
Yeah sure, I'm working on it. DOn't worry. Next release as soon as possible

**Comment by dgmstuart** [comment]
Hello - I still haven't had an email from you to security@dxw.com. 

I need to be able to privately email you regarding the process, and the rest of my team need visibility of this issue. Can you please send an email

**Comment by TweetPressFr** [comment]
I've done the update. Thanks again.

**Comment by dgmstuart** [comment]
Hi - thanks for that. I'm sad you weren't able to actually email us to discuss this :(

What version has the patch in it? I can try and work it out, but it would be good to hear it from you.

**Comment by TweetPressFr** [comment]
Oh sorry I did not want to avoid any talk. I really like to talk when it's about code :) I've just made my possible to fix thix quick !

**Comment by dgmstuart** [comment]
@TweetPressFr good to know. But what version has the patch in it?

**Comment by TweetPressFr** [comment]
6.2

**Comment by TweetPressFr** [comment]
;)
