### ISSUE TITLE
If metabox already is installed, activation of this plugin throws whole bunch of errors

### ISSUE THREAD

**Issue by senlin** [TweetPressFr/jm-twitter-cards#65]
For many themes I use the metabox plugin to enhance the backend. I also have developed a few plugins that are an extension of the metabox plugin, which gets installed with the TGM Plugin Activation Class if not yet installed.

Upon installing your plugin, this throws all kinds of Notices and errors.

I think at the very least your plugin should check whether or not the Metabox plugin already has been installed.

**Comment by TweetPressFr** [comment]
This is already taken into account : 

```
/**
 * A lot of themes and plugins
 * are using this framework
 * probably better to check this before
 */
if ( ! function_exists( 'rwmb_register_meta_boxes' ) ) {
	require_once ( JM_TC_DIR . 'vendor/rilwis/meta-box/meta-box.php' );
}
```
At the very least, your themes should check whether or not the Metabox plugin already has been installed by a plugin. Why ? Because plugins are loaded before themes.

**Comment by senlin** [comment]
This works only under the premise that the function to register the meta boxes is called `rwmb_register_meta_boxes`, which IMHO is the wrong assumption as it literally can be anything.

My plugins do a check whether the metabox plugin is active or not and if not show a warning and activate the TGM Plugin Activation Class. You can [have a look at one of my plugins](https://github.com/senlin/so-related-posts/blob/master/so-related-posts.php#L193-L231) to see how.

Hope that helps to improve your plugin.

**Comment by TweetPressFr** [comment]
Thanks a lot for your example but some installation rename plugins folder, what you gonna do with that ? the function ```rwmb_register_meta_boxes()``` is used to register new metabox with the framework, I do not understand why in your opinion it might be a wrong assumption because you have to use this function to add meta-boxes with the framework.

By the way ```array( &$this,``` is not necessary, you're refering to a reference. ```array( $this,``` is enough.

**Comment by senlin** [comment]
If I have 5 plugins that all are depending on the metabox plugin and they are all registering a new metabox with the function `rwmb_register_meta_boxes()`, what do you think will happen then?

**Comment by TweetPressFr** [comment]
I guess I see the issue but not the way you present it. It check if it already exists but it's not enough.
I'll fix it for the next update. It does not throw a fatal error but "already defined constants".

**Comment by TweetPressFr** [comment]
Notices you are experiencing were due to loading issue. Now on init, it will solve the problem.
