### ISSUE TITLE
No settings link appears

### ISSUE THREAD

**Issue by arnoldbird** [TweetPressFr/jm-twitter-cards#69]
I just pulled the latest code from git.  No settings link appears at wp-admin/plugins.php?plugin_status=search&paged=1&s=twitter

When the plugin is activated, the only link that appears is "Deactivate".

The plugin version is 7.7.  
Wordpress version 4.6.1.
PHP Version 5.6.11-1ubuntu3.4

See also: https://wordpress.org/support/topic/after-activating-settings-link-does-not-appear/
At that point I still was using the plugin code downloaded from https://wordpress.org/plugins/jm-twitter-cards
Since installing 7.7, I no longer see the "Settings" link on any of the three sites where I've tried to install the plugin.  

I'm not having this issue with other plugins.

**Comment by TweetPressFr** [comment]
Hi,

It requires composer install, otherwise it do not load anything.
