### ISSUE TITLE
New update causes tab issues with All in One SEO Pack

### ISSUE THREAD

**Issue by chrisaldrich** [TweetPressFr/jm-twitter-cards#70]
With the recent update to stable on WordPress.org 5 hours ago (v7.7) a change somewhere in the code is causing problems in the admin interface with the All in One SEO Pack.

In particular one can't switch between the two tabs in AIOSP interface "Main Settings" and "Social Settings". Only the details on the "Main Settings" tab can be seen and attempting to switch to "Social Settings" only changes the url (which then ends with <code>&action=edit#aioseop_opengraph_settings</code>. Attempting to switch back does nothing but change the URL to <code>&action=edit#aiosp</code>.

Disabling JM Twitter Cards and refreshing the post admin interface allows AIOSP to work properly and reenabling JMTC causes it to break again.

Thoughts?

Crossposted to https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/736

**Comment by chrisaldrich** [comment]
<a href="https://github.com/TweetPressFr/jm-twitter-cards/issues/70" class="u-in-reply-to"></a>After some additional testing this morning it appears that it's also causing problems with the built in WP editor and won't let one switch between the "Visual" and "Text" tabs. It also appears to remove the display of all of the text editing options/interface!

![tabs dont work](https://cloud.githubusercontent.com/assets/5882943/22406736/2305824c-e60d-11e6-831f-c70397b668ad.PNG)

Again, deactivating JM Twitter cards seems to remedy this issue.

**Comment by TweetPressFr** [comment]
should be fixed now with latest version
