### ISSUE TITLE
7.7 fatal error

### ISSUE THREAD

**Issue by ivanblagdan** [TweetPressFr/jm-twitter-cards#71]
Hi,
Just had this error pop up on one of our servers:
PHP Fatal error:  Class 'TokenToMe\\TwitterCards\\Loading' not found in /*edited-path*/wp-content/plugins/jm-twitter-cards/jm-twitter-cards.php on line 69, referer: https://www.google.com.br/

The bigger problem is that the plugin doesn't seem to have older versions available on https://wpackagist.org/search?q=jm-twitter-cards&type=any&search=. This resulted in a untested version of your plugin getting deployed when composer did the production build. Heres the entry in the composer.lock: https://dl.dropboxusercontent.com/s/fdv1qcgypzs5yg0/2017-01-30%20at%2013.37.png.
Could you look into having version numbers in your dist zip like other plugins?

**Comment by TweetPressFr** [comment]
Sorry I did not answer sooner, will fix this quick

**Comment by TweetPressFr** [comment]
is that ok now ? sorry I've no time at all :(

**Comment by TweetPressFr** [comment]
I've removed the composer files in svn which should fix this
