### ISSUE TITLE
No twitter:description when Excerpt option is set to "yes" and the post has no excerpt

### ISSUE THREAD

**Issue by tomdxw** [TweetPressFr/jm-twitter-cards#74]
`twitter:description` seems to be necessary for Twitter cards. At least according to [this validator](https://cards-dev.twitter.com/validator).

But when the Excerpt option is set to "yes" and there's no excerpt, `twitter:description` will not appear on the page.

Workaround: set the option to "no" (does not seem to affect the behaviour in any way except that now it works for all posts).

**Comment by TweetPressFr** [comment]
true, wil lbe fixed soon

**Comment by TweetPressFr** [comment]
fixed in 8.0

**Comment by tomdxw** [comment]
Thanks!
