### ISSUE TITLE
Incompatibility with Jupiter theme

### ISSUE THREAD

**Issue by ErinBaker** [TweetPressFr/jm-twitter-cards#77]
When JM Twitter Cards plugin is active, I get these console errors, causing the theme settings panel to not load. Using Artbees Jupiter theme 5.9.7

![image](https://user-images.githubusercontent.com/14230773/31159329-7b33c106-a8f2-11e7-9033-65051f61666a.png)

**Comment by TweetPressFr** [comment]
js is a mess, what a shame, sorry for that, got no time to work on this

**Comment by TweetPressFr** [comment]
fixed in 8.1
