### ISSUE TITLE
Two forms on one page leading to settings not getting saved

### ISSUE THREAD

**Issue by tomdxw** [TweetPressFr/jm-twitter-cards#78]
1. Visit /wp-admin/admin.php?page=jm_tc
2. Set "Home meta desc" to "blah"
3. Scroll to the bottom of the page and click "Save Changes"
4. The changes have not been saved

You can workaround this bug by pressing enter instead of clicking the submit button.

The tabs on this page do not work. Instead, the two forms are shown one after the other with one "Save Changes" button hidden.

Also note that the standard WordPress footer appears at the bottom of the viewport, and scrolls with the page content, meaning that one form field is obscured (and in some cases inaccessible). I'm not sure if this is related to the broken tabs or not.

**Comment by TweetPressFr** [comment]
I'm closing this cause it's fixed now.
