### ISSUE TITLE
card_type always returns summary

### ISSUE THREAD

**Issue by ioneill** [TweetPressFr/jm-twitter-cards#82]
/classes/admin/option.php line 67-71

Is:
`$cardType     = ( ! empty( $cardTypePost ) )
			? $cardTypePost
			: ! empty( $this->opts['twitterCardType'] )
				? $this->opts['twitterCardType']
				: '';`

Should be:
`$cardType     = ( ! empty( $cardTypePost ) )
			? $cardTypePost
			: ( ! empty( $this->opts['twitterCardType'] )
				? $this->opts['twitterCardType']
				: '' );`

**Comment by TweetPressFr** [comment]
in fact it always returns the general option which could be anything else but you're right it's a bug. Good catch !!! Will be fixed in next version

**Comment by TweetPressFr** [comment]
fixed in 9.3
