### ISSUE TITLE
thumbs.php: "Illegal string offset"-Warning

### ISSUE THREAD

**Issue by adlerweb** [TweetPressFr/jm-twitter-cards#84]
Current 9.4 (and afair also previous versions) raise the following warning for every page loaded (front- and backend):

`Warning: Illegal string offset 'twitterCardImgSize' in /var/www/html/wp-content/plugins/jm-twitter-cards/classes/thumbs.php on line 30`

For the code there that would be https://github.com/TweetPressFr/jm-twitter-cards/blob/c8e77d8638ff9c48730ba504857b7f7ce957fb89/classes/thumbs.php#L29
`$opts` is in this case not an array but an empty string. Workaround would be to return to the `default:`-state when `$opts` is not an array. I didn't look further into it due to #83, guess the root cause is somewhere in `jm_tc_get_options`.

**Comment by TweetPressFr** [comment]
hum I don't have this error, even if I install the plugin directly from wordpress.org, if course I have debug on, can you be more precise please. You may have found an error but I guess I don't understand it.

**Comment by adlerweb** [comment]
Ah - looks like a broken configuration causes this. I could reproduce it using Apache 2.4.25, PHP 7.2.6, MySQL 5.7 and Wordpress 4.9.6–de_DE. For testing I used the current [WP Docker image](https://hub.docker.com/_/wordpress/).

1. Install WP
2. Add/Activate Plugin (4.9)
3. Import empty configuration JSON (`{"tc":[""],"ie":[""]}`)
4. Enable Debugging (`error_reporting(E_ALL)`)

The empty configuration was an export from my site. Maybe the configuration wasn't there in older setups and hasn't been set during updates. After saving the (empty) config again using the HTML-form the error disappears.

**Comment by TweetPressFr** [comment]
ok thanks for the details, I'm closing it cause I think this won't happen in a "normal" context. Why do you use an empty configuration JSON ?

**Comment by adlerweb** [comment]
"The empty JSON was an export from my site". No idea why there was none, I can only guess back when I installed there was no default config generated and later updates never added it.
